// Homepage tokens - minimal data for fast loading
import feelsGuyImage from '@/assets/images/feels_guy.png';
export const HOMEPAGE_TOKENS = [
  {
    id: '1',
    address: 'feelsWojakMvNsD5n2R8rUPzFiHkq9JbgSstPVNkDPGb',
    name: 'Wojak',
    symbol: 'WOJAK',
    imageUrl: feelsGuyImage.src,
    launched: '3 days ago',
    price: 0.0423,
    priceChange24h: 8.9,
    marketCap: '$4.2M',
    volume24h: '$1.2M',
  },
  {
    id: '2',
    address: 'feelsDoomrP9uyrQpS3yn2Q5GeRFrYWnBDfvPKjLX84A',
    name: 'Doomer',
    symbol: 'DOOMER',
    imageUrl: feelsGuyImage.src,
    launched: '5 days ago',
    price: 0.0089,
    priceChange24h: -3.2,
    marketCap: '$890K',
    volume24h: '$120K',
  },
  {
    id: '3',
    address: 'feelsCoomrGPT4NL8z3xZpYjQcBJknmggY3htVKe3SUBz',
    name: 'Coomer',
    symbol: 'COOMER',
    imageUrl: feelsGuyImage.src,
    launched: '10 days ago',
    price: 0.0057,
    priceChange24h: -8.3,
    marketCap: '$1.9M',
    volume24h: '$320K',
  },
  {
    id: '4',
    address: 'feelsGrugJ3fYgKwpt5HqNYoiFcF3WgC5Nz7VXeMBBBq',
    name: 'Grug',
    symbol: 'GRUG',
    imageUrl: feelsGuyImage.src,
    launched: '1 day ago',
    price: 0.0912,
    priceChange24h: 67.3,
    marketCap: '$9.1M',
    volume24h: '$3.4M',
  },
  {
    id: '5',
    address: 'feelsBloomWGMKdCK9SqtAjeuK6DSQSz3cDitYCYGBtfE',
    name: 'Bloomer',
    symbol: 'BLOOMER',
    imageUrl: feelsGuyImage.src,
    launched: '3 days ago',
    price: 0.0756,
    priceChange24h: 34.2,
    marketCap: '$7.5M',
    volume24h: '$2.8M',
  },
  {
    id: '6',
    address: 'feelsZoomrABNqRdyVtDD9zK3voj4UBEn8FbNsWXEQgB',
    name: 'Zoomer',
    symbol: 'ZOOMER',
    imageUrl: feelsGuyImage.src,
    launched: '2 weeks ago',
    price: 0.0078,
    priceChange24h: -12.4,
    marketCap: '$780K',
    volume24h: '$95K',
  },
  {
    id: '7',
    address: 'feelsNPCMintK5TQaWjM3BRJpnkYxBsHcqKzWWUFYg27M',
    name: 'NPC',
    symbol: 'NPC',
    imageUrl: feelsGuyImage.src,
    launched: '1 week ago',
    price: 0.0111,
    priceChange24h: 0.0,
    marketCap: '$1.1M',
    volume24h: '$111K',
  },
  {
    id: '8',
    address: 'feelsChadQbQg8cUKW3pEfkYQwzJhfvj5u8fUvJgpQfG',
    name: 'Chad',
    symbol: 'CHAD',
    imageUrl: feelsGuyImage.src,
    launched: '4 days ago',
    price: 0.0342,
    priceChange24h: 23.1,
    marketCap: '$3.4M',
    volume24h: '$890K',
  },
] as const;